import Header from "@/components/header/Header"
import "./globals.css"
import Footer from "@/components/footer/Footer"
import { Roboto } from "next/font/google"
import style from "./layout.module.scss"
import classNames from "classnames"

const roboto = Roboto({
  subsets: ["cyrillic"],
  weight: ["400", "500", "700"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang='ru'>
      <body className={classNames(roboto.className, style.body)}>
        <Header />
        <main className={style.main}>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
